#!/usr/bin/env node
/**
 * scripts/build.mjs
 *
 * Reads content JSON files and renders them into static HTML pages.
 * No runtime dependencies — pure Node.js template string rendering.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, copyFileSync, readdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

const GOOGLE_CLIENT_ID  = process.env.GOOGLE_CLIENT_ID  || 'REPLACE_WITH_CLIENT_ID';
const PROXY_URL = 'https://learn-proxy.funfairlabs.com/chat';
const GCS_BUCKET = process.env.GCS_BUCKET || 'learning-monkey-switch';
const ALLOWED_USERS_KEY = 'learn-allowed-users.json';

// ── Helpers ──────────────────────────────────────────────────────────────────

function read(path) {
  return existsSync(path) ? readFileSync(path, 'utf8') : null;
}

function readJSON(path) {
  const raw = read(path);
  if (!raw) return null;
  try { return JSON.parse(raw); } catch { return null; }
}

function formatDate(iso) {
  try {
    return new Date(iso).toLocaleDateString('en-GB', {
      weekday: 'long', day: 'numeric', month: 'long', year: 'numeric'
    });
  } catch { return iso; }
}

function renderCard(resource) {
  return `
    <a href="${resource.url}" target="_blank" rel="noopener noreferrer" class="resource-card">
      <span class="resource-title">${resource.title}</span>
      <span class="resource-why">${resource.why_now}</span>
      <span class="resource-link-icon">↗</span>
    </a>`;
}

function renderSection(data) {
  if (!data) return '';
  return `
  <section class="topic-section">
    <h2 class="topic-title">${data.topic}</h2>
    <div class="highlight-card">
      <span class="highlight-label">This week's highlight</span>
      <a href="${data.highlight.url}" target="_blank" rel="noopener noreferrer" class="highlight-link">
        ${data.highlight.title} ↗
      </a>
      <p class="highlight-summary">${data.highlight.summary}</p>
    </div>
    <div class="resources-grid">
      ${data.resources.map(renderCard).join('')}
    </div>
    <div class="claude-take">
      <span class="take-label">Claude's take</span>
      <p>${data.claude_take}</p>
    </div>
    <div class="section-meta">Updated ${formatDate(data.generated_at)}</div>
  </section>`;
}

// ── Index page ────────────────────────────────────────────────────────────────

function buildIndex() {
  const topics = [
    'mcp-ai', 'gcp-infra', 'nextjs-fullstack', 'devtools-workflow', 'tech-news',
    'architecture', 'leadership', 'networks', 'uk-education'
  ];
  const sections = topics
    .map(slug => readJSON(join(ROOT, 'content', 'recommendations', `${slug}.json`)))
    .map(renderSection)
    .join('\n');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>learn · funfairlabs</title>

  <link rel="stylesheet" href="/css/style.css">
</head>
<body>
  <script>
    /* Dynamic colour palette — matches funfairlabs.com */
    (function(){
      const ranges=[[0,35],[165,260],[280,340]];
      const r=ranges[Math.floor(Math.random()*ranges.length)];
      const h=Math.floor(Math.random()*(r[1]-r[0])+r[0]);
      const root=document.documentElement;
      root.style.setProperty('--pal-h', h);
      root.style.setProperty('--accent',     'hsl('+h+',78%,42%)');
      root.style.setProperty('--accent-d',   'hsl('+h+',76%,30%)');
      root.style.setProperty('--accent-soft','hsl('+h+',82%,95%)');
      root.style.setProperty('--accent-t',   'hsla('+h+',78%,42%,0.13)');
    })();
  </script>
  <header class="site-header">
    <div class="header-inner">
      <a href="/" class="wordmark">funfairlabs<span class="wordmark-learn">/learn</span></a>
      <nav class="header-nav">
        <a href="/learn/" class="nav-link nav-link--auth" id="study-link">study</a>
        <a href="/plans/" class="nav-link nav-link--plans" id="plans-link">my plans</a>
        <button class="btn-header-signin" id="header-signin-btn" onclick="window.learnAuth && window.learnAuth.signIn()">
          Sign in
        </button>
      </nav>
    </div>
  </header>

  <main>
    <section class="hero">
      <p class="hero-kicker">Claude recommends</p>
      <h1 class="hero-headline">What's worth<br><em>your attention</em><br>this week</h1>
      <p class="hero-sub">Curated weekly by Claude with live web search. No AI slop — just what's actually relevant right now.</p>
    </section>

    <div class="topics-wrapper">
      ${sections || '<p class="empty-state">Content is being generated. Check back shortly.</p>'}
    </div>
  </main>

  <footer class="site-footer">
    <p>Generated by Claude · <a href="https://github.com/funfairlabs-incubator/funfairlabs-learn">source</a></p>
  </footer>

  <script>
    window.LEARN_CONFIG = {
      clientId: "${GOOGLE_CLIENT_ID}",
      gcsBucket: "${GCS_BUCKET}",
      allowedUsersKey: "${ALLOWED_USERS_KEY}",
      proxyUrl: "${PROXY_URL}"
    };
  </script>
  <script src="/js/auth.js"></script>
  <script>
    // Show plans link only when user is authenticated
    window.addEventListener('learn:auth', (e) => {
      if (e.detail.authenticated) {
        document.getElementById('plans-link').classList.add('visible');
        document.getElementById('study-link').classList.add('visible');
        const btn = document.getElementById('header-signin-btn');
        if (btn) btn.classList.add('hidden');
      }
    });
  </script>
</body>
</html>`;

  mkdirSync(join(ROOT, 'public'), { recursive: true });
  writeFileSync(join(ROOT, 'public', 'index.html'), html);
  console.log('✅ Built: public/index.html');
}

// ── Plans index page (auth-gated shell) ───────────────────────────────────────

function buildPlansIndex() {
  // Read all plan markdown files to generate nav
  const plansDir = join(ROOT, 'content', 'plans');
  const planFiles = existsSync(plansDir)
    ? readdirSync(plansDir).filter(f => f.endsWith('.md'))
    : [];

  const planMeta = {
    'mcp-training-plan.md':     { title: 'MCP Deep-Dive', icon: '⚡' },
    'gcp-guide.md':             { title: 'GCP / Cloud Run / GAE', icon: '☁️' },
    'nextjs-patterns.md':       { title: 'Next.js & Full-Stack', icon: '▲' },
    'ai-claude-patterns.md':    { title: 'AI & Claude Integration', icon: '◆' },
    'architecture-guide.md':    { title: 'Architecture & System Design', icon: '⬡' },
    'leadership-guide.md':      { title: 'Leadership & Team Craft', icon: '◎' },
    'networks-guide.md':        { title: 'Networks & How the Internet Works', icon: '⟳' },
    'uk-education-guide.md':    { title: 'UK School Curriculum Y7–13', icon: '✎' },
  };

  const planLinks = planFiles.map(f => {
    const meta = planMeta[f] || { title: f.replace('.md', ''), icon: '📄' };
    const slug = f.replace('.md', '');
    return `<a href="/plans/${slug}/" class="plan-card">
      <span class="plan-icon">${meta.icon}</span>
      <span class="plan-title">${meta.title}</span>
      <span class="plan-arrow">→</span>
    </a>`;
  }).join('\n');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>plans · learn · funfairlabs</title>

  <link rel="stylesheet" href="/css/style.css">
  <meta name="google-signin-client_id" content="${GOOGLE_CLIENT_ID}">
</head>
<body class="plans-page">
  <script>
    /* Dynamic colour palette — matches funfairlabs.com */
    (function(){
      const ranges=[[0,35],[165,260],[280,340]];
      const r=ranges[Math.floor(Math.random()*ranges.length)];
      const h=Math.floor(Math.random()*(r[1]-r[0])+r[0]);
      const root=document.documentElement;
      root.style.setProperty('--pal-h', h);
      root.style.setProperty('--accent',     'hsl('+h+',78%,42%)');
      root.style.setProperty('--accent-d',   'hsl('+h+',76%,30%)');
      root.style.setProperty('--accent-soft','hsl('+h+',82%,95%)');
      root.style.setProperty('--accent-t',   'hsla('+h+',78%,42%,0.13)');
    })();
  </script>
  <header class="site-header">
    <div class="header-inner">
      <a href="/" class="wordmark">funfairlabs<span class="wordmark-learn">/learn</span></a>
      <nav class="header-nav">
        <a href="/learn/" class="nav-link nav-link--auth visible">study</a>
        <a href="/plans/" class="nav-link nav-link--plans visible">my plans</a>
      </nav>
    </div>
  </header>

  <!-- Auth gate: shown when not authenticated -->
  <div class="auth-gate" id="auth-gate">
    <div class="auth-gate-inner">
      <p class="auth-kicker">private section</p>
      <h2>Training plans &<br>personal guides</h2>
      <p class="auth-sub">Sign in with your Google account to access your learning plans.</p>
      <button class="btn-signin" id="signin-btn" onclick="window.learnAuth.signIn()">
        <svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M17.64 9.2c0-.637-.057-1.251-.164-1.84H9v3.481h4.844c-.209 1.125-.843 2.078-1.796 2.717v2.258h2.908c1.702-1.567 2.684-3.874 2.684-6.615z" fill="#4285F4"/>
          <path d="M9 18c2.43 0 4.467-.806 5.956-2.18l-2.908-2.259c-.806.54-1.837.86-3.048.86-2.344 0-4.328-1.584-5.036-3.711H.957v2.332A8.997 8.997 0 009 18z" fill="#34A853"/>
          <path d="M3.964 10.71A5.41 5.41 0 013.682 9c0-.593.102-1.17.282-1.71V4.958H.957A8.996 8.996 0 000 9c0 1.452.348 2.827.957 4.042l3.007-2.332z" fill="#FBBC05"/>
          <path d="M9 3.58c1.321 0 2.508.454 3.44 1.345l2.582-2.58C13.463.891 11.426 0 9 0A8.997 8.997 0 00.957 4.958L3.964 6.29C4.672 4.163 6.656 3.58 9 3.58z" fill="#EA4335"/>
        </svg>
        Sign in with Google
      </button>
      <p class="auth-note">Access is restricted. If you should have access, contact the admin.</p>
    </div>
  </div>

  <!-- Content: shown when authenticated + authorised -->
  <main class="plans-main" id="plans-content" style="display:none">
    <section class="plans-hero">
      <h1>Your learning plans</h1>
      <p>Claude-maintained training plans and guides. Versioned in git, regenerated on request.</p>
    </section>
    <div class="plans-grid">
      ${planLinks || '<p class="empty-state">No plans yet. They\'ll appear here once generated.</p>'}
    </div>
  </main>

  <footer class="site-footer">
    <p>Generated by Claude · <a href="https://github.com/funfairlabs-incubator/funfairlabs-learn">source</a></p>
  </footer>

  <script>
    window.LEARN_CONFIG = {
      clientId: "${GOOGLE_CLIENT_ID}",
      gcsBucket: "${GCS_BUCKET}",
      allowedUsersKey: "${ALLOWED_USERS_KEY}",
      proxyUrl: "${PROXY_URL}"
    };
  </script>
  <script src="/js/auth.js"></script>
</body>
</html>`;

  mkdirSync(join(ROOT, 'public', 'plans'), { recursive: true });
  writeFileSync(join(ROOT, 'public', 'plans', 'index.html'), html);
  console.log('✅ Built: public/plans/index.html');
}

// ── Individual plan pages ─────────────────────────────────────────────────────

function buildPlanPages() {
  const plansDir = join(ROOT, 'content', 'plans');
  if (!existsSync(plansDir)) return;

  const planFiles = readdirSync(plansDir).filter(f => f.endsWith('.md'));

  for (const file of planFiles) {
    const slug = file.replace('.md', '');
    const markdown = readFileSync(join(plansDir, file), 'utf8');
    // Extract title from first H1
    const titleMatch = markdown.match(/^#\s+(.+)$/m);
    const title = titleMatch ? titleMatch[1] : slug;

    // Very simple markdown→HTML for headings, paragraphs, code blocks, lists
    const body = simpleMarkdown(markdown);

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} · learn · funfairlabs</title>

  <link rel="stylesheet" href="/css/style.css">
  <meta name="google-signin-client_id" content="${GOOGLE_CLIENT_ID}">
</head>
<body class="plan-page">
  <script>
    /* Dynamic colour palette — matches funfairlabs.com */
    (function(){
      const ranges=[[0,35],[165,260],[280,340]];
      const r=ranges[Math.floor(Math.random()*ranges.length)];
      const h=Math.floor(Math.random()*(r[1]-r[0])+r[0]);
      const root=document.documentElement;
      root.style.setProperty('--pal-h', h);
      root.style.setProperty('--accent',     'hsl('+h+',78%,42%)');
      root.style.setProperty('--accent-d',   'hsl('+h+',76%,30%)');
      root.style.setProperty('--accent-soft','hsl('+h+',82%,95%)');
      root.style.setProperty('--accent-t',   'hsla('+h+',78%,42%,0.13)');
    })();
  </script>
  <header class="site-header">
    <div class="header-inner">
      <a href="/" class="wordmark">funfairlabs<span class="wordmark-learn">/learn</span></a>
      <nav class="header-nav">
        <a href="/plans/" class="nav-link">← plans</a>
      </nav>
    </div>
  </header>

  <div class="auth-gate auth-gate--inline" id="auth-gate">
    <div class="auth-gate-inner">
      <p>This content is private. <button class="btn-signin-inline" onclick="window.learnAuth.signIn()">Sign in with Google →</button></p>
    </div>
  </div>

  <main class="plan-content" id="plan-content" style="display:none">
    <article class="plan-article">
      ${body}
    </article>
  </main>

  <footer class="site-footer">
    <p>Generated by Claude · <a href="/plans/">← back to plans</a></p>
  </footer>

  <script>
    window.LEARN_CONFIG = {
      clientId: "${GOOGLE_CLIENT_ID}",
      gcsBucket: "${GCS_BUCKET}",
      allowedUsersKey: "${ALLOWED_USERS_KEY}",
      proxyUrl: "${PROXY_URL}"
    };
  </script>
  <script src="/js/auth.js"></script>
</body>
</html>`;

    mkdirSync(join(ROOT, 'public', 'plans', slug), { recursive: true });
    writeFileSync(join(ROOT, 'public', 'plans', slug, 'index.html'), html);
    console.log(`✅ Built: public/plans/${slug}/index.html`);
  }
}

// Very simple Markdown renderer (enough for training plan content)
function simpleMarkdown(md) {
  let html = md
    // Fenced code blocks
    .replace(/```(\w*)\n([\s\S]*?)```/g, (_, lang, code) =>
      `<pre class="code-block"><code class="lang-${lang}">${escapeHtml(code.trim())}</code></pre>`)
    // Headings
    .replace(/^#### (.+)$/gm, '<h4>$1</h4>')
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    // Bold + italic
    .replace(/\*\*\*(.+?)\*\*\*/g, '<strong><em>$1</em></strong>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    // Inline code
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    // Links
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" target="_blank" rel="noopener">$1</a>')
    // Unordered lists (simple)
    .replace(/^[-*] (.+)$/gm, '<li>$1</li>')
    // Ordered lists
    .replace(/^\d+\. (.+)$/gm, '<li>$1</li>')
    // Horizontal rule
    .replace(/^---$/gm, '<hr>')
    // Blockquote
    .replace(/^> (.+)$/gm, '<blockquote>$1</blockquote>')
    // Paragraphs (double newline)
    .replace(/\n\n(?!<[hlu]|<pre|<blockquote|<hr)/g, '</p><p>')
    // Wrap stray li elements in ul
    .replace(/(<li>[\s\S]+?<\/li>)/g, (match) => `<ul>${match}</ul>`)
    // Cleanup
    .replace(/<\/ul>\s*<ul>/g, '');

  return `<p>${html}</p>`;
}

function escapeHtml(str) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

// ── Copy static assets ────────────────────────────────────────────────────────

function copyAssets() {
  const cssDir = join(ROOT, 'public', 'css');
  const jsDir = join(ROOT, 'public', 'js');
  mkdirSync(cssDir, { recursive: true });
  mkdirSync(jsDir, { recursive: true });

  // CSS and JS are written directly to public/ (source of truth)
  // Nothing to copy — they're already there
  console.log('✅ Assets in place');
}

// ── Learn page (auth-gated study interface) ───────────────────────────────────

function buildLearnPage() {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>study · learn · funfairlabs</title>

  <link rel="stylesheet" href="/css/style.css">
  <link rel="stylesheet" href="/css/learn.css">
  <meta name="google-signin-client_id" content="${GOOGLE_CLIENT_ID}">
</head>
<body class="learn-page">
  <script>
    /* Dynamic colour palette — matches funfairlabs.com */
    (function(){
      const ranges=[[0,35],[165,260],[280,340]];
      const r=ranges[Math.floor(Math.random()*ranges.length)];
      const h=Math.floor(Math.random()*(r[1]-r[0])+r[0]);
      const root=document.documentElement;
      root.style.setProperty('--pal-h', h);
      root.style.setProperty('--accent',     'hsl('+h+',78%,42%)');
      root.style.setProperty('--accent-d',   'hsl('+h+',76%,30%)');
      root.style.setProperty('--accent-soft','hsl('+h+',82%,95%)');
      root.style.setProperty('--accent-t',   'hsla('+h+',78%,42%,0.13)');
    })();
  </script>
  <header class="site-header">
    <div class="header-inner">
      <a href="/" class="wordmark">funfairlabs<span class="wordmark-learn">/learn</span></a>
      <nav class="header-nav">
        <div id="user-chip" class="user-chip" style="display:none"></div>
      </nav>
    </div>
  </header>

  <!-- Auth gate -->
  <div class="auth-gate" id="auth-gate">
    <div class="auth-gate-inner">
      <p class="auth-kicker">study with claude</p>
      <h2>Your personal<br>learning space</h2>
      <p class="auth-sub">Sign in to explore any topic with a guide built just for you.</p>
      <button class="btn-signin" id="signin-btn" onclick="window.learnAuth.signIn()">
        <svg width="18" height="18" viewBox="0 0 18 18" fill="none">
          <path d="M17.64 9.2c0-.637-.057-1.251-.164-1.84H9v3.481h4.844c-.209 1.125-.843 2.078-1.796 2.717v2.258h2.908c1.702-1.567 2.684-3.874 2.684-6.615z" fill="#4285F4"/>
          <path d="M9 18c2.43 0 4.467-.806 5.956-2.18l-2.908-2.259c-.806.54-1.837.86-3.048.86-2.344 0-4.328-1.584-5.036-3.711H.957v2.332A8.997 8.997 0 009 18z" fill="#34A853"/>
          <path d="M3.964 10.71A5.41 5.41 0 013.682 9c0-.593.102-1.17.282-1.71V4.958H.957A8.996 8.996 0 000 9c0 1.452.348 2.827.957 4.042l3.007-2.332z" fill="#FBBC05"/>
          <path d="M9 3.58c1.321 0 2.508.454 3.44 1.345l2.582-2.58C13.463.891 11.426 0 9 0A8.997 8.997 0 00.957 4.958L3.964 6.29C4.672 4.163 6.656 3.58 9 3.58z" fill="#EA4335"/>
        </svg>
        Sign in with Google
      </button>
      <p class="auth-note">Access is restricted to family members.</p>
    </div>
  </div>

  <!-- Main content — shown after auth -->
  <div id="learn-content" style="display:none" class="learn-content-wrapper">

    <!-- Child mode banner -->
    <div id="child-mode-banner" class="child-mode-banner" style="display:none">
      <span class="banner-icon">◆</span>
      <span class="banner-text"></span>
    </div>

    <!-- Topic entry screen -->
    <div class="topic-entry">
      <div class="topic-entry-inner">
        <p class="topic-kicker" id="topic-kicker-adult">What would you like to explore?</p>
        <p class="topic-kicker topic-kicker--child" id="topic-kicker-child" style="display:none">What are you studying?</p>
        <form id="topic-form" class="topic-form" autocomplete="off">
          <input
            id="topic-input"
            type="text"
            class="topic-input"
            placeholder="e.g. World War Two, photosynthesis, quadratic equations…"
            autocomplete="off"
            spellcheck="false"
          >
          <button type="submit" class="btn-start">
            <span class="btn-start-text-adult">Build study guide →</span>
            <span class="btn-start-text-child" style="display:none">Let's explore →</span>
          </button>
        </form>
        <p class="topic-hint" id="topic-hint-adult">
          Claude will create a structured guide you can work through, ask questions about, and adapt.
        </p>
        <p class="topic-hint topic-hint--child" id="topic-hint-child" style="display:none">
          Claude will ask you what you know and help you go further — it won't do your homework, but it will help you think.
        </p>
      </div>
    </div>

    <!-- Chat interface — shown once topic is chosen -->
    <div id="chat-area" class="chat-area" style="display:none">
      <div class="chat-header">
        <div class="chat-topic-info">
          <span class="chat-topic-label">Exploring:</span>
          <span id="current-topic-label" class="chat-topic-name"></span>
        </div>
        <button id="new-topic-btn" class="btn-new-topic">← new topic</button>
      </div>

      <div id="chat-messages" class="chat-messages"></div>

      <div class="chat-input-area">
        <form id="chat-form" class="chat-form">
          <textarea
            id="chat-input"
            class="chat-input"
            placeholder="Ask a question or say what you're thinking…"
            rows="1"
            autocomplete="off"
          ></textarea>
          <button type="submit" id="send-btn" class="btn-send">
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
              <path d="M14 8L2 2l2 6-2 6 12-6z" fill="currentColor"/>
            </svg>
          </button>
        </form>
        <p class="chat-disclaimer" id="chat-disclaimer-child" style="display:none">
          Claude will help you think — it won't write answers for you.
        </p>
      </div>
    </div>

  </div><!-- /learn-content-wrapper -->

  <footer class="site-footer">
    <p>Powered by Claude · <a href="/">← home</a></p>
  </footer>

  <script>
    window.LEARN_CONFIG = {
      clientId: "${GOOGLE_CLIENT_ID}",
      gcsBucket: "${GCS_BUCKET}",
      allowedUsersKey: "${ALLOWED_USERS_KEY}",
      proxyUrl: "${PROXY_URL}"
    };
  </script>
  <script src="/js/auth.js"></script>
  <script src="/js/personas.js"></script>
  <script src="/js/learn.js"></script>
  <script>
    // Adjust UI text once we know the persona
    window.addEventListener('learn:auth', (e) => {
      const user = e.detail.user;
      const isChild = user.role === 'child';

      // Topic entry copy
      document.getElementById('topic-kicker-adult').style.display = isChild ? 'none' : '';
      document.getElementById('topic-kicker-child').style.display = isChild ? '' : 'none';
      document.getElementById('topic-hint-adult').style.display   = isChild ? 'none' : '';
      document.getElementById('topic-hint-child').style.display   = isChild ? '' : 'none';
      document.querySelector('.btn-start-text-adult').style.display = isChild ? 'none' : '';
      document.querySelector('.btn-start-text-child').style.display = isChild ? '' : 'none';

      // Chat disclaimer
      const disclaimer = document.getElementById('chat-disclaimer-child');
      if (disclaimer) disclaimer.style.display = isChild ? '' : 'none';
    });
  </script>
</body>
</html>`;

  mkdirSync(join(ROOT, 'public', 'learn'), { recursive: true });
  writeFileSync(join(ROOT, 'public', 'learn', 'index.html'), html);
  console.log('✅ Built: public/learn/index.html');
}

// ── Run ───────────────────────────────────────────────────────────────────────

buildIndex();
buildPlansIndex();
buildPlanPages();
buildLearnPage();
copyAssets();

console.log('\n✨ Build complete → public/');
